name: Build Python App

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build and package Python app
      run: |
        pyinstaller --onefile --name papercut-exporter app_runner.py

    - name: List contents of current directory
      run: ls

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: papercut-exporter-windows
        path: dist/papercut-exporter.exe
